<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');

$customMetadata = [
    'Types' => $item->value('dcterms:type',['all' => true]),
    'Categories' => $item->value('mare:categoricalFocus',['all' => true]),
    'Places' => $item->value('mare:populatedPlaceName',['all' => true]),
    'States' => $item->value('mare:stateTerritoryName',['all' => true]),
    'Countries' => $item->value('mare:countryName',['all' => true]),
    'Geographic Focus' => $item->value('mare:geographicalFocus',['all' => true]),
    'Material Focus' => $item->value('mare:materialFocus',['all' => true]),
    'Accrual Method' => $item->value('dcterms:accrualMethod',['all' => true]),
]
?>

<!-- Metadata for a collecting project. -->
<?php if($item->resourceClass() && $item->resourceClass()->id() == 133): ?>

    <div class="grid-x grid-padding-x">
        <div class="resource-title cell medium-12">
            <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
        </div>
        <?php if (count($itemMedia) > 0): ?>
        <div class="cell medium-3">
            <?php foreach ($itemMedia as $media): ?>
                <?php echo $media->render(); ?>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        <div class="cell medium-9">
            <?php if(($description = $item->displayDescription()) && ($description !== '')): ?>
                <p><?php echo $description; ?></p>
            <?php endif; ?>

            <?php if($institutions = $item->value('mare:originatingInstitution',['all' => true])): ?>
                <?php foreach($institutions as $institution): ?>
                    <?php if ($institutionResource = $institution->valueResource()): ?>
                    <p class="institution"><?php echo $institutionResource->linkPretty('fullsize'); ?></p>
                    <?php else: ?>
                    <p class="institution"><?php echo $institution->asHtml(); ?></p>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if( $item->value('mare:collectingUrl')): ?>
                <?php echo $this->hyperlink('Contribute to This Project', $item->value('mare:collectingUrl')->uri(),[
                  'class' => 'o-icon-external button',
                  'aria-label' => 'External',
                ]); ?>
            <?php endif; ?>

            <?php if ($item->value('mare:collectionUrl')): ?>
                <?php echo $this->hyperlink('Project Website', $item->value('mare:collectionUrl')->uri(), [ 
                      'class' => 'o-icon-external button',
                      'aria-label' => 'External',
                ]); ?>
            <?php endif; ?>

            <?php foreach ($customMetadata as $key => $values): ?>
            <?php if ((count($values) > 0)): ?>
            <div class="property">
                <h4><?php echo $key; ?></h4>
                <div class="values">
                <?php foreach($values as $value): ?>
                    <div class="value"><?php echo $value; ?></div>
                <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    

<?php else: ?>
<!-- Metadata for everything else. -->
<div class="grid-x grid-padding-x">

    <div class="resource-title cell medium-12">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    </div>

    <div class="cell medium-12">
        <?php foreach ($itemMedia as $media): ?>
            <?php echo $media->render(); ?>
        <?php endforeach; ?>
    </div>

    <div class="cell medium-9">
        <?php $itemSets = $item->itemSets(); ?>
            <?php foreach($itemSets as $itemSet): ?>
            <?php if($itemSet->resourceClass() && $itemSet->resourceClass()->id() == 133): ?>
                 <p>This item originates from <a href="<?php echo $itemSet->value('mare:collectionUrl')->uri(); ?>"><?php echo $itemSet->value('mare:collectionUrl'); ?></a>.</p>
            <?php endif; ?>
            <?php endforeach; ?>
        <?php $this->trigger('view.show.before'); ?>
        <?php echo $item->displayValues(); ?>

        <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>
        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>
 <?php endif; ?>




