<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');

$description = $item->displayDescription();
$institutions = $item->value('mare:originatingInstitution',['all' => true]);
$types = $item->value('dcterms:type',['all' => true]);
$categories = $item->value('mare:categoricalFocus',['all' => true]);
$placeNames = $item->value('mare:populatedPlaceName',['all' => true]);
$stateNames = $item->value('mare:stateTerritoryName',['all' => true]);
$countries = $item->value('mare:countryName',['all' => true]);
$geographicalFocuses = $item->value('mare:geographicalFocus',['all' => true]);
$materialFocuses = $item->value('mare:materialFocus',['all' => true]);
$accrualMethods = $item->value('dcterms:accrualMethod',['all' => true]);
?>



<?php if($item->resourceClass() && $item->resourceClass()->id() == 24): ?>

    <div class="grid-x grid-padding-x">
        <div class="resource-title cell medium-12">
            <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
        </div>
        <div class="cell medium-3">
            <?php foreach ($itemMedia as $media): ?>
                <?php echo $media->render(); ?>
            <?php endforeach; ?>
        </div>
        <div class="cell medium-9">
            <?php if($description): ?>
                <p><?php echo $item->displayDescription(); ?></p>
            <?php endif; ?>

            <?php if($institutions): ?>
                <?php foreach($institutions as $institution): ?>
                    <p class="institution"><?php echo $institution; ?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if( $item->value('mare:collectingUrl')): ?>
                <?php echo $this->hyperlink('Contribute to This Project', $item->value('mare:collectingUrl')->uri(),['class' => 'button']); ?>
            <?php endif; ?>

            <?php if ($item->value('mare:collectionUrl')): ?>
                <?php echo $this->hyperlink('Learn More', $item->value('mare:collectionUrl')->uri()); ?>
            <?php endif; ?>

            <div class="property">
                <h4></h4>
                <div class="values"></div>
            </div>

            <?php if($types): ?>
                <div class="property">
                    <h4>Type</h4>
                    <?php foreach ($types as $type): ?>
                        <div class="values"><?php echo $type; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($categories): ?>
                <div class="property">
                    <h4>Categorical Focus</h4>
                    <?php foreach($categories as $category): ?>
                        <div class="values"><?php echo $category; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($placeNames): ?>
                <div class="property">
                    <h4>Place Name</h4>
                    <?php foreach($placeNames as $placeName): ?>
                        <div class="values"><?php echo $placeName; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($stateNames): ?>
                <div class="property">
                    <h4>State or Territory</h4>
                    <?php foreach($stateNames as $stateName): ?>
                        <div class="values"><?php echo $stateName; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($countries): ?>
                <div class="property">
                    <h4>Country</h4>
                    <?php foreach($countries as $country): ?>
                        <div class="values"><?php echo $country; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($geographicalFocuses): ?>
                <div class="property">
                    <h4>Geographical Focus</h4>
                    <?php foreach($geographicalFocuses as $geographicalFocus): ?>
                        <div class="values"><?php echo $geographicalFocus; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($materialFocuses): ?>
                <div class="property">
                    <h4>Geographical Focus</h4>
                    <?php foreach($materialFocuses as $materialFocus): ?>
                        <div class="values"><?php echo $materialFocus; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($accrualMethods): ?>
                <div class="property">
                    <h4>Geographical Focus</h4>
                    <?php foreach($accrualMethods as $accrualMethod): ?>
                        <div class="values"><?php echo $accrualMethod; ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>          
        </div>
    </div>

<?php else: ?>
<div class="grid-x grid-padding-x">

    <div class="resource-title cell medium-12">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    </div>

    <div class="cell medium-12">
        <?php foreach ($itemMedia as $media): ?>
            <?php echo $media->render(); ?>
        <?php endforeach; ?>
    </div>

    <div class="cell medium-9">
        <?php $itemSets = $item->itemSets(); ?>
            <?php foreach($itemSets as $itemSet): ?>
            <?php if($itemSet->resourceClass() && $itemSet->resourceClass()->id() == 114): ?>
                 <p>This item originates from <a href="<?php echo $itemSet->value('mare:collectionUrl'); ?>"><?php echo $itemSet->value('dcterms:title'); ?></a></p>
            <?php endif; ?>
            <?php endforeach; ?>
        <?php $this->trigger('view.show.before'); ?>
        <?php echo $item->displayValues(); ?>

        <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>
        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>
 <?php endif; ?>




