<?php
$escape = $this->plugin('escapeHtml');
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/collecting.css'));

$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile('//cdn.jsdelivr.net/npm/foundation-sites@6.5.3/dist/js/foundation.min.js', 'text/javascript', [
  'integrity' => 'sha256-/PFxCnsMh+nTuM0k3VJCRch1gwnCfKjaP8rJNq5SoBg= sha384-9ksAFjQjZnpqt6VtpjMjlp2S0qrGbcwF/rvrLUg2vciMhwc1UJJeAAOLuJ96w+Nj sha512-UMSn6RHqqJeJcIfV1eS2tPKCjzaHkU/KqgAnQ7Nzn0mLicFxaVhm9vq7zG5+0LALt15j1ljlg8Fp9PT1VGNmDw==',
  'crossorigin' => 'anonymous'
]);
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/collecting-form.js'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$siteUrl = $site->url();
$siteTitle = $site->title();

if ($userBar) {
  $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    
        <div id="offCanvas" class="off-canvas position-left" data-off-canvas>
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical', 'siteUrl' => $siteUrl]); ?>
            <div class="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header>
                <?php echo $this->partial('common/header-dropdown', ['site' => $site, 'siteUrl' => $siteUrl, 'siteTitle' => $siteTitle]); ?>
            </header>
            <div class="grid-container">           
                <?php echo $this->partial('common/site-title', ['siteUrl' => $siteUrl, 'siteTitle' => $siteTitle]); ?>
            </div>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
            <footer>
                <div class="grid-x grid-margin-x">
                <?php $footerLogos = [
                         $this->themeSettingAssetUrl('footer_logo_one') => $this->themeSetting('footer_logo_link_one'),
                         $this->themeSettingAssetUrl('footer_logo_two') => $this->themeSetting('footer_logo_link_two'),
                         $this->themeSettingAssetUrl('footer_logo_three') => $this->themeSetting('footer_logo_link_three'),
                         $this->themeSettingAssetUrl('footer_logo_four') => $this->themeSetting('footer_logo_link_four')
                    ] ?>
                    <?php foreach ($footerLogos as $key => $value): ?>
                        <?php if($value): ?>
                            <a href="<?php echo $this->escapeHtml($value); ?>"><img src="<?php echo $this->escapeHtml($key); ?>"></a>
                        <?php else: ?>
                            <img src="<?php echo $this->escapeHtml($key); ?>">
                        <?php endif; ?>
                    <?php endforeach; ?>

                <div class="cell small-12">
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
                </div>
                </div>
            </footer>
        </div>
        <script>
          $(document).foundation();
        </script>
    </body>
</html>
